package app.slimboard.emoji

import android.content.Context
import android.graphics.Paint
import android.os.Handler
import android.os.Looper

class Emoji(val chars: String, val name: String, val variants: List<String>) {
    val searchName: String = name.lowercase()
}

class EmojiGroup(val name: String, val icon: String, val emojis: List<Emoji>)

/**
 * Emoji list loaded once from assets/emoji/emoji.txt (generated by tools/gen-emoji.ps1 from Unicode's
 * emoji-test.txt). Format per line: group-index TAB emoji TAB name [TAB variant,variant,...].
 * Emoji the system font cannot render are dropped at load time.
 */
object EmojiData {

    private val GROUPS = listOf(
        "Smileys" to "😀",
        "People" to "🧑",
        "Animals & nature" to "🐻",
        "Food & drink" to "🍔",
        "Travel & places" to "🚗",
        "Activities" to "⚽",
        "Objects" to "💡",
        "Symbols" to "🔣",
        "Flags" to "🏁",
    )

    @Volatile var groups: List<EmojiGroup>? = null
        private set
    @Volatile var available = true
        private set

    private var loading = false
    private val waiters = ArrayList<(List<EmojiGroup>) -> Unit>()
    private val main = Handler(Looper.getMainLooper())

    /** Calls [onReady] on the main thread, immediately if already loaded. */
    fun ensureLoaded(context: Context, onReady: (List<EmojiGroup>) -> Unit) {
        groups?.let { onReady(it); return }
        waiters.add(onReady)
        if (loading) return
        loading = true
        val assets = context.assets
        Thread({
            val result = try { parse(assets.open("emoji/emoji.txt").bufferedReader().readLines()) } catch (e: Exception) { available = false; emptyList() }
            main.post {
                groups = result
                loading = false
                val w = waiters.toList()
                waiters.clear()
                for (cb in w) cb(result)
            }
        }, "slimboard-emoji").start()
    }

    private fun parse(lines: List<String>): List<EmojiGroup> {
        val paint = Paint()
        val buckets = Array(GROUPS.size) { ArrayList<Emoji>() }
        for (line in lines) {
            if (line.isEmpty() || line[0] == '#') continue
            val parts = line.split('\t')
            if (parts.size < 3) continue
            val g = parts[0].toIntOrNull() ?: continue
            if (g !in buckets.indices) continue
            val chars = parts[1]
            if (!paint.hasGlyph(chars)) continue
            val variants = if (parts.size > 3 && parts[3].isNotEmpty()) parts[3].split(',').filter { paint.hasGlyph(it) } else emptyList()
            buckets[g].add(Emoji(chars, parts[2], variants))
        }
        return GROUPS.mapIndexed { i, (name, icon) -> EmojiGroup(name, icon, buckets[i]) }.filter { it.emojis.isNotEmpty() }
    }

    /**
     * All query words must appear in the name. Ranking: exact name, then name starts with the query,
     * then a word in the name starts with the query, then plain substring. Shorter names win ties,
     * so "fire" beats "firefighter" and "fire engine".
     */
    fun search(query: String, limit: Int = 48): List<Emoji> {
        val gs = groups ?: return emptyList()
        val q = query.trim().lowercase()
        if (q.isEmpty()) return emptyList()
        val words = q.split(' ').filter { it.isNotEmpty() }
        val scored = ArrayList<Pair<Int, Emoji>>()
        for (g in gs) for (e in g.emojis) {
            val name = e.searchName
            if (!words.all { name.contains(it) }) continue
            val rank = when {
                name == q -> 0
                name.startsWith(q) -> 1
                name.contains(" $q") || name.contains(":$q") || name.contains("-$q") -> 2
                else -> 3
            }
            scored.add((rank * 1000 + name.length) to e)
        }
        scored.sortBy { it.first }
        return scored.take(limit).map { it.second }
    }
}
