# Generates app/src/main/assets/emoji/emoji.txt from Unicode's emoji-test.txt.
#
# Output format, one emoji per line:
#   <group index>TAB<emoji>TAB<name>[TAB<skin-tone variant>,<variant>,...]
# Group indices follow EmojiData.GROUPS: 0 Smileys & Emotion, 1 People & Body, 2 Animals & Nature,
# 3 Food & Drink, 4 Travel & Places, 5 Activities, 6 Objects, 7 Symbols, 8 Flags.
# Skin-tone variants are folded into their base emoji so the picker shows one cell with a long-press menu.
#
# Usage: powershell -File tools/gen-emoji.ps1 [-Version 16.0] [-Source <local emoji-test.txt>]
param(
    [string]$Version = "16.0",
    [string]$Source = ""
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$outDir = Join-Path $root "app\src\main\assets\emoji"
$outFile = Join-Path $outDir "emoji.txt"

if ($Source -eq "") {
    $Source = Join-Path $env:TEMP "emoji-test-$Version.txt"
    if (-not (Test-Path $Source)) {
        $url = "https://unicode.org/Public/emoji/$Version/emoji-test.txt"
        Write-Output "Downloading $url"
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $url -OutFile $Source -UseBasicParsing
    }
}

$groupIndex = @{
    "Smileys & Emotion" = 0
    "People & Body"     = 1
    "Animals & Nature"  = 2
    "Food & Drink"      = 3
    "Travel & Places"   = 4
    "Activities"        = 5
    "Objects"           = 6
    "Symbols"           = 7
    "Flags"             = 8
}
$toneWords = "light skin tone|medium-light skin tone|medium skin tone|medium-dark skin tone|dark skin tone"

# Ordered list of base entries; key -> entry with Group, Emoji, Name, Variants
$order = New-Object System.Collections.Generic.List[string]
$entries = @{}
$group = -1

foreach ($line in [IO.File]::ReadLines($Source)) {
    if ($line.StartsWith("# group: ")) {
        $g = $line.Substring(9).Trim()
        if ($groupIndex.ContainsKey($g)) { $group = $groupIndex[$g] } else { $group = -1 }
        continue
    }
    if ($group -lt 0 -or $line.Length -eq 0 -or $line.StartsWith("#")) { continue }
    # 1F600 ; fully-qualified # 😀 E1.0 grinning face
    $m = [regex]::Match($line, '^([0-9A-F ]+?)\s*;\s*(fully-qualified|component)\s*#\s*(\S+)\s+E\d+\.\d+\s+(.*)$')
    if (-not $m.Success) { continue }
    if ($m.Groups[2].Value -eq "component") { continue }
    $emoji = $m.Groups[3].Value
    $name = $m.Groups[4].Value.Trim()

    # Skin tone variant? Strip ": <tone>[, <tone>]" and attach to the base.
    $baseName = [regex]::Replace($name, ":\s*($toneWords)(,\s*($toneWords))*", "")
    $isVariant = $baseName -ne $name
    $key = "$group|$baseName"

    if ($isVariant) {
        if ($entries.ContainsKey($key)) {
            $entries[$key].Variants.Add($emoji)
        }
        # Variants whose base was not seen (rare ordering quirk) are dropped.
        continue
    }
    if (-not $entries.ContainsKey($key)) {
        $entries[$key] = [pscustomobject]@{
            Group    = $group
            Emoji    = $emoji
            Name     = $name
            Variants = New-Object System.Collections.Generic.List[string]
        }
        $order.Add($key)
    }
}

New-Item -ItemType Directory -Force $outDir | Out-Null
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("# Generated by tools/gen-emoji.ps1 from Unicode emoji-test.txt v$Version. Unicode data files license: https://www.unicode.org/license.txt")
foreach ($key in $order) {
    $e = $entries[$key]
    $lineOut = "$($e.Group)`t$($e.Emoji)`t$($e.Name)"
    if ($e.Variants.Count -gt 0) { $lineOut += "`t" + ($e.Variants -join ",") }
    [void]$sb.AppendLine($lineOut)
}
$utf8 = New-Object System.Text.UTF8Encoding($false)
[IO.File]::WriteAllText($outFile, $sb.ToString(), $utf8)

$variantCount = ($entries.Values | ForEach-Object { $_.Variants.Count } | Measure-Object -Sum).Sum
Write-Output ("Wrote {0}: {1} emoji, {2} skin-tone variants folded in, {3:N0} KB" -f $outFile, $order.Count, $variantCount, ((Get-Item $outFile).Length / 1KB))
