# Generates app/src/main/assets/dict/en.txt: "word count" per line, most frequent first.
#
# Sources (downloaded once into %TEMP%):
#   count_1w.txt   Peter Norvig's unigram counts from the Google Web Trillion Word Corpus (norvig.com/ngrams)
#   words_alpha.txt dwyl/english-words, a plain list of valid English words used as a validity filter
# The intersection keeps common real words (including inflections) and drops web junk tokens.
# A small list of contractions is added because the corpus split them on apostrophes.
#
# Usage: powershell -File tools/gen-dict.ps1 [-Max 70000]
param(
    [int]$Max = 70000
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$outDir = Join-Path $root "app\src\main\assets\dict"
$outFile = Join-Path $outDir "en.txt"
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$countsFile = Join-Path $env:TEMP "count_1w.txt"
$wordsFile = Join-Path $env:TEMP "words_alpha.txt"
if (-not (Test-Path $countsFile)) {
    Write-Output "Downloading https://norvig.com/ngrams/count_1w.txt"
    Invoke-WebRequest -Uri "https://norvig.com/ngrams/count_1w.txt" -OutFile $countsFile -UseBasicParsing
}
if (-not (Test-Path $wordsFile)) {
    Write-Output "Downloading https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt"
    Invoke-WebRequest -Uri "https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt" -OutFile $wordsFile -UseBasicParsing
}

$valid = New-Object 'System.Collections.Generic.HashSet[string]'
foreach ($w in [IO.File]::ReadLines($wordsFile)) { $t = $w.Trim(); if ($t.Length -gt 0) { [void]$valid.Add($t) } }
Write-Output ("Valid word list: {0:N0} words" -f $valid.Count)

# Short words that are real but easy to confuse with junk; keep them regardless of list membership.
$keepShort = @("a", "i", "an", "as", "at", "be", "by", "do", "go", "he", "hi", "if", "in", "is", "it", "me", "my", "no", "of", "ok", "on", "or", "so", "to", "up", "us", "we")

$out = New-Object System.Collections.Generic.List[string]
$counts = @{}
foreach ($line in [IO.File]::ReadLines($countsFile)) {
    $parts = $line.Split("`t")
    if ($parts.Length -lt 2) { continue }
    $word = $parts[0]
    $count = [long]$parts[1]
    if ($word.Length -eq 1 -and $word -ne "a" -and $word -ne "i") { continue }
    if ($word.Length -le 2 -and -not ($keepShort -contains $word)) { continue }
    if ($word.Length -gt 2 -and -not $valid.Contains($word)) { continue }
    $counts[$word] = $count
    $out.Add("$word $count")
    if ($out.Count -ge $Max) { break }
}

# Contractions: give each the count of its apostrophe-less form, or a solid default.
$contractions = @("don't","can't","won't","i'm","it's","you're","we're","they're","isn't","aren't","wasn't","weren't",
    "wouldn't","couldn't","shouldn't","didn't","doesn't","haven't","hasn't","hadn't","i've","you've","we've","they've",
    "i'll","you'll","he'll","she'll","we'll","they'll","i'd","you'd","he'd","she'd","we'd","they'd","let's","that's",
    "there's","here's","what's","who's","where's","how's","o'clock","y'all","ma'am","ain't","she's","he's","could've",
    "would've","should've","might've","must've","who'd","who'll","what'll","that'll","there'd","there'll")
foreach ($c in $contractions) {
    $bare = $c.Replace("'", "")
    $n = 5000000
    if ($counts.ContainsKey($bare)) { $n = $counts[$bare] }
    $out.Add("$c $n")
}

New-Item -ItemType Directory -Force $outDir | Out-Null
$header = "# Generated by tools/gen-dict.ps1 from norvig.com/ngrams/count_1w.txt filtered by dwyl/english-words. Format: word count"
$utf8 = New-Object System.Text.UTF8Encoding($false)
[IO.File]::WriteAllLines($outFile, @($header) + $out, $utf8)
Write-Output ("Wrote {0}: {1:N0} words, {2:N0} KB" -f $outFile, $out.Count, ((Get-Item $outFile).Length / 1KB))
