# Generates app/src/main/assets/dict/en.txt: "word count" per line, most frequent first.
#
# Sources (downloaded once into %TEMP%):
#   count_1w.txt   Peter Norvig's unigram counts from the Google Web Trillion Word Corpus (norvig.com/ngrams)
#   words_alpha.txt dwyl/english-words, a plain list of valid English words used as a validity filter
# The intersection keeps common real words (including inflections) and drops web junk tokens.
# A small list of contractions is added because the corpus split them on apostrophes.
#
# Usage: powershell -File tools/gen-dict.ps1 [-Max 70000]
param(
    [int]$Max = 70000
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$outDir = Join-Path $root "app\src\main\assets\dict"
$outFile = Join-Path $outDir "en.txt"
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$countsFile = Join-Path $env:TEMP "count_1w.txt"
$wordsFile = Join-Path $env:TEMP "words_alpha.txt"
if (-not (Test-Path $countsFile)) {
    Write-Output "Downloading https://norvig.com/ngrams/count_1w.txt"
    Invoke-WebRequest -Uri "https://norvig.com/ngrams/count_1w.txt" -OutFile $countsFile -UseBasicParsing
}
if (-not (Test-Path $wordsFile)) {
    Write-Output "Downloading https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt"
    Invoke-WebRequest -Uri "https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt" -OutFile $wordsFile -UseBasicParsing
}

$valid = New-Object 'System.Collections.Generic.HashSet[string]'
foreach ($w in [IO.File]::ReadLines($wordsFile)) { $t = $w.Trim(); if ($t.Length -gt 0) { [void]$valid.Add($t) } }
Write-Output ("Valid word list: {0:N0} words" -f $valid.Count)

# Short words that are real but easy to confuse with junk; keep them regardless of list membership.
$keepShort = @("a", "i", "an", "as", "at", "be", "by", "do", "go", "he", "hi", "if", "in", "is", "it", "me", "my", "no", "of", "ok", "on", "or", "so", "to", "up", "us", "we")

# Apostrophe-less contraction forms that the word list treats as valid. Dropping them lets
# autocorrect turn "dont" into "don't". Genuine words that also happen to be contraction stems
# (ill, well, hell, shell, id, wed, were, its) are kept.
$exclude = @("dont","im","doesnt","didnt","isnt","arent","wasnt","werent","wouldnt","couldnt","shouldnt","havent",
    "hasnt","hadnt","youre","theyre","ive","youve","weve","theyve","youll","theyll","thats","theres","heres","whats",
    "whos","wheres","hows","lets","cant","wont","hes","shes","aint","yall","oclock","maam","couldve","wouldve",
    "shouldve","mightve","mustve","thatll","therell","whatll")

$out = New-Object System.Collections.Generic.List[string]
$counts = @{}
foreach ($line in [IO.File]::ReadLines($countsFile)) {
    $parts = $line.Split("`t")
    if ($parts.Length -lt 2) { continue }
    $word = $parts[0]
    $count = [long]$parts[1]
    if ($word.Length -eq 1 -and $word -ne "a" -and $word -ne "i") { continue }
    if ($word.Length -le 2 -and -not ($keepShort -contains $word)) { continue }
    if ($word.Length -gt 2 -and -not $valid.Contains($word)) { continue }
    $counts[$word] = $count
    if ($exclude -contains $word) { continue }
    $out.Add("$word $count")
    if ($out.Count -ge $Max) { break }
}

# Contractions. The corpus split them on apostrophes, so counts are assigned by tier: the everyday
# ones sit among the top few hundred words of real text, the rest are still common.
$tier1 = @("don't","can't","i'm","it's","that's","didn't","doesn't","you're","isn't","won't","i've","i'll","we're",
    "they're","let's","there's","what's","wasn't","he's","she's","you'll","we'll","couldn't","wouldn't","aren't","haven't")
$tier2 = @("weren't","shouldn't","hasn't","hadn't","you've","we've","they've","he'll","she'll","they'll","i'd","you'd",
    "he'd","she'd","we'd","they'd","here's","who's","where's","how's","o'clock","y'all","ma'am","ain't","could've",
    "would've","should've","might've","must've","who'd","who'll","what'll","that'll","there'd","there'll")
foreach ($c in $tier1) { $out.Add("$c 1200000000") }
foreach ($c in $tier2) { $out.Add("$c 150000000") }

New-Item -ItemType Directory -Force $outDir | Out-Null
$header = "# Generated by tools/gen-dict.ps1 from norvig.com/ngrams/count_1w.txt filtered by dwyl/english-words. Format: word count"
$utf8 = New-Object System.Text.UTF8Encoding($false)
[IO.File]::WriteAllLines($outFile, @($header) + $out, $utf8)
Write-Output ("Wrote {0}: {1:N0} words, {2:N0} KB" -f $outFile, $out.Count, ((Get-Item $outFile).Length / 1KB))
